using PoC1_LegacyAnalyzer_Web.Models;
using System.Text;

namespace PoC1_LegacyAnalyzer_Web.Services
{
    public class ReportService : IReportService
    {
        public async Task<string> GenerateReportAsync(CodeAnalysisResult analysis, string aiAnalysis, string fileName, string analysisType)
        {
            return await Task.FromResult(GenerateReportContent(analysis, aiAnalysis, fileName, analysisType));
        }

        public async Task<byte[]> GenerateReportAsBytesAsync(CodeAnalysisResult analysis, string aiAnalysis, string fileName, string analysisType)
        {
            var reportContent = GenerateReportContent(analysis, aiAnalysis, fileName, analysisType);
            return await Task.FromResult(Encoding.UTF8.GetBytes(reportContent));
        }

        public string GenerateReportContent(CodeAnalysisResult analysis, string aiAnalysis, string fileName, string analysisType)
        {
            var report = new StringBuilder();

            // Header
            report.AppendLine($"# AI-Enhanced Code Analysis Report");
            report.AppendLine($"*File: {fileName} | Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}*");
            report.AppendLine();

            // Executive Summary
            report.AppendLine("## Executive Summary");
            var riskLevel = GetRiskLevel(analysis, analysisType);
            var timeEstimate = GetTimeEstimate(analysis, analysisType);

            report.AppendLine($"**Analysis Type**: {analysisType.ToUpper()}");
            report.AppendLine($"**Risk Level**: {riskLevel}");
            report.AppendLine($"**Estimated Effort**: {timeEstimate}");
            report.AppendLine($"**Business Priority**: {GetBusinessPriority(analysis)}");
            report.AppendLine();

            // Roslyn Static Analysis
            report.AppendLine("## Roslyn Static Analysis");
            report.AppendLine($"- **Classes**: {analysis.ClassCount}");
            report.AppendLine($"- **Methods**: {analysis.MethodCount}");
            report.AppendLine($"- **Properties**: {analysis.PropertyCount}");
            report.AppendLine($"- **Dependencies**: {analysis.UsingCount} using statements");
            report.AppendLine();

            // Key Components
            if (analysis.Classes.Any())
            {
                report.AppendLine("### Key Components Identified");
                foreach (var className in analysis.Classes.Take(5))
                {
                    report.AppendLine($"- `{className}` class");
                }
                if (analysis.Classes.Count > 5)
                {
                    report.AppendLine($"- ... and {analysis.Classes.Count - 5} additional classes");
                }
                report.AppendLine();
            }

            // AI Analysis
            report.AppendLine("## AI Analysis Summary");
            report.AppendLine(aiAnalysis);
            report.AppendLine();

            // Business Impact
            report.AppendLine("## Business Impact Assessment");
            report.AppendLine($"**Modernization Value**: {GetModernizationValue(analysis)}");
            report.AppendLine($"**Technical Debt Level**: {GetTechnicalDebt(analysis)}");
            report.AppendLine($"**Migration Complexity**: {GetMigrationComplexity(analysis)}");
            report.AppendLine();

            // Next Steps
            report.AppendLine("## Recommended Next Steps");
            report.AppendLine("1. **Immediate**: Address high-priority items identified by AI analysis");
            report.AppendLine("2. **Short-term**: Plan migration timeline based on complexity assessment");
            report.AppendLine("3. **Long-term**: Establish modernization standards for development team");
            report.AppendLine();

            // Footer
            report.AppendLine("---");
            report.AppendLine("*Report generated by AI-Enhanced Legacy Code Migration Assistant*");
            report.AppendLine($"*Analysis Date: {DateTime.Now:yyyy-MM-dd HH:mm:ss}*");

            return report.ToString();
        }

        private string GetRiskLevel(CodeAnalysisResult analysis, string analysisType)
        {
            var score = analysis.ClassCount * 2 + analysis.MethodCount + analysis.UsingCount;
            return analysisType switch
            {
                "security" => score > 50 ? "🔴 HIGH - Immediate security review needed" :
                             score > 20 ? "🟡 MEDIUM - Security improvements recommended" :
                             "🟢 LOW - Basic security practices in place",
                "performance" => score > 100 ? "🔴 HIGH - Performance bottlenecks likely" :
                                score > 50 ? "🟡 MEDIUM - Optimization opportunities exist" :
                                "🟢 LOW - Performance adequate for current scale",
                "migration" => score > 80 ? "🔴 HIGH - Complex migration required" :
                              score > 40 ? "🟡 MEDIUM - Moderate migration effort" :
                              "🟢 LOW - Straightforward migration path",
                _ => score > 60 ? "🟡 MEDIUM - Moderate modernization effort" : "🟢 LOW - Minimal changes needed"
            };
        }

        private string GetTimeEstimate(CodeAnalysisResult analysis, string analysisType)
        {
            var complexity = analysis.ClassCount + (analysis.MethodCount / 5);
            return complexity switch
            {
                > 50 => "8-12 weeks (Complex project)",
                > 25 => "4-6 weeks (Medium project)",
                > 10 => "2-3 weeks (Small project)",
                _ => "1-2 weeks (Simple refactoring)"
            };
        }

        private string GetBusinessPriority(CodeAnalysisResult analysis)
        {
            return analysis.MethodCount switch
            {
                > 50 => "HIGH - Core business system",
                > 20 => "MEDIUM - Important component",
                _ => "LOW - Support utility"
            };
        }

        private string GetModernizationValue(CodeAnalysisResult analysis)
        {
            return analysis.ClassCount switch
            {
                > 10 => "HIGH - Significant ROI from modernization",
                > 5 => "MEDIUM - Moderate benefits expected",
                _ => "LOW - Consider as part of larger initiative"
            };
        }

        private string GetTechnicalDebt(CodeAnalysisResult analysis)
        {
            var debtScore = analysis.UsingCount + (analysis.MethodCount / analysis.ClassCount);
            return debtScore switch
            {
                > 20 => "HIGH - Substantial refactoring needed",
                > 10 => "MEDIUM - Some cleanup required",
                _ => "LOW - Well-maintained code"
            };
        }

        private string GetMigrationComplexity(CodeAnalysisResult analysis)
        {
            return (analysis.ClassCount * analysis.MethodCount) switch
            {
                > 500 => "HIGH - Requires dedicated migration team",
                > 100 => "MEDIUM - Experienced developers needed",
                _ => "LOW - Standard migration process"
            };
        }
    }
}
